#!/bin/bash

# Generate authors file in the desired format
echo "# File @generated by authors.sh. DO NOT EDIT."
echo "# This file lists all contributors to the repository."
echo "# See authors.sh to make modifications."
echo

# Add your name and your friend's name manually
echo "- Yordanos Tarekegn <jordantarsh@gmail.com>"
echo "- Samson Mekonnen <yitesam@gmail.com>"

# Generate the list of other contributors
git shortlog -sn --all | awk '{printf "- %s <%s>\n", $2, $3}'

